### ISSUE TITLE
Store SPKI only

### ISSUE THREAD

**Issue by snoe** [snoe/deedum#12]
From @makeworld-the-better-one

> I'm happy to see TOFU support in deedum! If I can make a suggestion: Store the hash of the SubjectPublicKeyInfo part of the cert, and not the hash of the entire cert. This idea comes from this report which Solderpunk shared on the mailing list a little while ago, in the "Thoughts on TOFU" thread. The SPKI portion of the cert changes less often, so there will be less false positives of TOFU errors.

 So I looked at some keys with an asn.1 parser - some seem to have an spki section, but others just have a public key. I guess I would store either? 

What about the chain? Am I supposed to prompt the user for which cert in the chain to trust? Is that how it works?

**Comment by makeworld-the-better-one** [comment]
Hello!

You should check out my TOFU post btw, it might be helpful: `gemini://makeworld.gq/gemlog/2020-07-03-tofu-rec.gmi`

> So I looked at some keys with an asn.1 parser - some seem to have an spki section, but others just have a public key. I guess I would store either?

Could you explain more what you mean? Also keep in mind it's best to hash binary content, not parsed text content.

There should only be one SPKI section, that contains the key information. On [this wiki page](https://en.wikipedia.org/wiki/X.509#Structure_of_a_certificate) you can see that at the top level there is:
> - Subject Public Key Info 
>   - Public Key Algorithm
>   - Subject Public Key

What you want to do is hash the binary version of Subject Public Key Info, if possible. But as I mentioned in that post, it's not so bad to just hash the entire binary cert if you have to, because no one on Gemini is really changing other parts of the cert.

> What about the chain? Am I supposed to prompt the user for which cert in the chain to trust? Is that how it works?

Most servers are only serving a single self-signed cert. So you should be always using the first cert in the "chain", because it is the actual server cert.

**Comment by idc-snoe** [comment]
Thank you @makeworld-the-better-one that was helpful.
